Repository SU-SWS/ood_giving_site, pull requests merged in 2021-12, with the labels that each got.

#239 ADAPT-4122: Sync the slideshow with the modal slideshow
  src/components/composite/oodGallerySlideshow.js
Labels: size/xs

#240 ADAPT-3949: Updated Gatsby to v4, along with dependencies.
  gatsby-config.js
  package-lock.json
  package.json
  src/components/partials/sbLink.js
  src/scss/components/composite/_accordion.scss
  src/scss/components/simple/_cta-link.scss
  src/utilities/config.js
Labels: size/xl, patch

#241 Major Release: 2.0.0
  gatsby-config.js
  package-lock.json
  package.json
  src/components/composite/oodGallerySlideshow.js
  src/components/partials/sbLink.js
  src/scss/components/composite/_accordion.scss
  src/scss/components/simple/_cta-link.scss
  src/utilities/config.js
Labels: size/xl, major
