Repository SU-SWS/ood_giving_site, pull requests merged in 2022-10, with the labels that each got.

#277 new endowed positions data
  src/components/endowed-positions/EndowedPositionsFooter.js
  src/fixtures/endowedPositions.json
Labels: feature

#279 manual update position holder
  src/fixtures/endowedPositions.json
Labels: fix

#278 To be merged on Oct 7 - Release v2.2.4 - new endowed positions data
  src/components/endowed-positions/EndowedPositionsFooter.js
  src/fixtures/endowedPositions.json
Labels: patch
