Repository SU-SWS/ood_giving_site, pull requests merged in 2022-08, with the labels that each got.

#261 ADAPT-000: Update endowed positions data
  src/fixtures/endowedPositions.json
Labels: feature

#264 Release V 2.1.4
  src/fixtures/endowedPositions.json
Labels: patch

#263 ADAPT-000: move gsb position, updated date update
  src/components/endowed-positions/EndowedPositionsFooter.js
  src/fixtures/endowedPositions.json
Labels: feature

#265 Release V2.1.5
  src/components/endowed-positions/EndowedPositionsFooter.js
  src/fixtures/endowedPositions.json
Labels: patch

#238 ADAPT-4099: Upgrade storyblok to v2 bridge
  README.md
  dev/README.md
  dev/localhost-key.pem
  dev/localhost.pem
  package-lock.json
  package.json
  src/pages/editor.js
Labels: patch, size/m

#267 Merge main into dev
  README.md
  dev/README.md
  dev/localhost-key.pem
  dev/localhost.pem
  package-lock.json
  package.json
  src/components/media/storyImage.js
  src/components/partials/htmlHead.js
  src/pages/editor.js
Labels: minor

#260 Feat/storyblok endowed positions search comp
  gatsby-config.js
  src/components/components.js
  src/components/endowed-positions/EndowedPositionsSearch.js
  src/components/endowed-positions/EndowedPositionsSearchPicker.js
Labels: feature
