Repository SU-SWS/ood_giving_site, pull requests merged in 2022-06, with the labels that each got.

#249 Professorships | @wmui51
  gatsby-browser.js
  gatsby-config.js
  package-lock.json
  package.json
  src/components/endowed-positions/EndowedPositionsFooter.js
  src/components/endowed-positions/EndowedPositionsHeader.js
  src/components/endowed-positions/EndowedPositionsNav.js
  src/components/endowed-positions/EndowedPositionsPagination.js
  src/constants/ENDOWED_POSITIONS_MAP.json
  src/fixtures/endowedPositions.json
  src/pages/endowed-positions/search.js
  src/pages/endowed-positions/{EndowedPositionsMapJson.to}.js
  src/scss/components/endowed-positions/index.scss
  src/scss/components/index.scss
Labels: size/xl, patch, feature

#252 Release 2.1.0
  .github/workflows/release.yml
  gatsby-browser.js
  gatsby-config.js
  package-lock.json
  package.json
  src/components/endowed-positions/EndowedPositionsFooter.js
  src/components/endowed-positions/EndowedPositionsHeader.js
  src/components/endowed-positions/EndowedPositionsNav.js
  src/components/endowed-positions/EndowedPositionsPagination.js
  src/constants/ENDOWED_POSITIONS_MAP.json
  src/fixtures/endowedPositions.json
  src/pages/endowed-positions/search.js
  src/pages/endowed-positions/{EndowedPositionsMapJson.to}.js
  src/scss/components/endowed-positions/index.scss
  src/scss/components/index.scss
Labels: minor

#254 Professorships | Fast follows - update schools and dataset, add page metadata
  src/constants/ENDOWED_POSITIONS_MAP.json
  src/fixtures/endowedPositions.json
  src/pages/endowed-positions/search.js
  src/pages/endowed-positions/{EndowedPositionsMapJson.to}.js
Labels: feature

#255 Release V2.1.1
  src/constants/ENDOWED_POSITIONS_MAP.json
  src/fixtures/endowedPositions.json
  src/pages/endowed-positions/search.js
  src/pages/endowed-positions/{EndowedPositionsMapJson.to}.js
  static/_redirects
Labels: patch

#256 Professorships | Update title text on pages
  src/constants/ENDOWED_POSITIONS_MAP.json
  src/fixtures/endowedPositions.json
  src/pages/endowed-positions/search.js
  src/pages/endowed-positions/{EndowedPositionsMapJson.to}.js
Labels: feature

#257 Professorships - Update to Labels and SEO Metadata
  src/constants/ENDOWED_POSITIONS_MAP.json
  src/fixtures/endowedPositions.json
  src/pages/endowed-positions/search.js
  src/pages/endowed-positions/{EndowedPositionsMapJson.to}.js
Labels: patch
