Repository SU-SWS/ood_giving_site, pull requests merged in 2022-09, with the labels that each got.

#270 NoJira: Endowed positions update data
  src/components/endowed-positions/EndowedPositionsFooter.js
  src/constants/ENDOWED_POSITIONS_MAP.json
  src/fixtures/endowedPositions.json
Labels: feature

#271 Release V2.2.1
  README.md
  gatsby-config.js
  src/components/components.js
  src/components/endowed-positions/EndowedPositionsFooter.js
  src/components/endowed-positions/EndowedPositionsSearch.js
  src/components/endowed-positions/EndowedPositionsSearchPicker.js
  src/constants/ENDOWED_POSITIONS_MAP.json
  src/fixtures/endowedPositions.json
Labels: patch

#269 NoJira: Style the endowed positions search component
  src/components/endowed-positions/EndowedPositionsSearch.js
  src/scss/components/endowed-positions/index.scss
Labels: patch, feature

#272 remove endowed positions sub page dropdown
  src/components/endowed-positions/EndowedPositionsHeader.js
  src/components/endowed-positions/EndowedPositionsNav.js
  src/scss/components/endowed-positions/index.scss
Labels: feature

#273 ADAPT-5295 | @jdwjdwjdw | Fix storyblok preview link not working in new window
  src/pages/editor.js
Labels: fix

#274 Release v2.2.2
  src/components/endowed-positions/EndowedPositionsHeader.js
  src/components/endowed-positions/EndowedPositionsNav.js
  src/components/endowed-positions/EndowedPositionsSearch.js
  src/pages/editor.js
  src/scss/components/endowed-positions/index.scss
Labels: patch

#275 update to Sarafan
  src/fixtures/endowedPositions.json
Labels: feature

#276 Release v2.2.3 - Sarafan data
  src/fixtures/endowedPositions.json
Labels: patch
