Repository SU-SWS/ood_giving_site, pull requests merged in 2025-09, with the labels that each got.

#583 Release: v4.2.13
  static/_redirects
Labels: patch, retro

#606 404 errors and static rendering cache
  AGENTS.md
  app/(storyblok)/[[...slug]]/page.tsx
  app/endowed-positions/[slug]/page.tsx
  app/sitemap.ts
  components/EndowedPositions/EndowedPositionsPagination.tsx
  docs/adr/0005-404-handling-and-build-time-caching.md
  next.config.ts
  package-lock.json
  utilities/data/getAllStories.ts
  utilities/data/getGlobalAlerts.ts
  utilities/data/getSearchConfigBlok.ts
  utilities/data/getStoryData.ts
  utilities/storyblok.tsx
  utilities/validateSlugPath.ts
Labels: AI Developer

#607 Release: v6.1.0
  AGENTS.md
  app/(storyblok)/[[...slug]]/page.tsx
  app/endowed-positions/[slug]/page.tsx
  app/sitemap.ts
  components/EndowedPositions/EndowedPositionsPagination.tsx
  docs/adr/0005-404-handling-and-build-time-caching.md
  next.config.ts
  package-lock.json
  utilities/data/getAllStories.ts
  utilities/data/getGlobalAlerts.ts
  utilities/data/getSearchConfigBlok.ts
  utilities/data/getStoryData.ts
  utilities/storyblok.tsx
  utilities/validateSlugPath.ts
Labels: minor

#613 Release/v6.1.1
  components/BasicCard/BasicCard.tsx
  components/CampaignCard/CampaignCard.tsx
  components/EmbedVideo/EmbedVideo.styles.ts
  components/EmbedVideo/EmbedVideo.tsx
  components/GallerySlideshow/Slide.tsx
  components/Image/AspectRatioImage.tsx
  components/Image/FullWidthImage.tsx
  components/Image/Image.styles.ts
  components/Image/StoryImage.tsx
  components/Media/MediaWrapper.styles.ts
  components/Media/MediaWrapper.tsx
  components/OverhangCard/OverhangCard.styles.ts
  components/QuoteCard/QuoteCard.tsx
  components/Storyblok/PageHeader/HeaderFullWidthImage.tsx
  components/Storyblok/PageHeader/HeaderSmallImage.tsx
  components/Storyblok/SbBasicCard.tsx
  components/Storyblok/SbCampaignPage/CampaignHero.tsx
  components/Storyblok/SbCampaignPage/SbCampaignHeader.tsx
  components/Storyblok/SbInteriorPage.tsx
  components/Storyblok/SbMegaMenu/SbMegaMenu.styles.ts
  components/Storyblok/SbMegaMenu/SbMegaMenuCard.tsx
  components/Storyblok/SbQuoteCard.tsx
  components/Storyblok/SbStoryImage.tsx
  components/Storyblok/SbTileCard.tsx
  components/Storyblok/partials/PageLayout.tsx
  components/TileCard/TileCard.styles.ts
  components/TileCard/TileCard.tsx
  styles/tables.css
  utilities/getImageSources.ts
Labels: patch
